# Generated by Django 4.2.16 on 2024-10-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_udc_deletedby_alter_udc_deletedon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='udc',
            name='Header',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='udc',
            name='ParentId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='udc',
            name='RelationId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='udc',
            name='val1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='udc',
            name='val2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
