# Generated by Django 4.2.16 on 2024-10-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_udc_header_alter_udc_parentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='udc',
            name='IsHeader',
            field=models.BooleanField(default=True),
        ),
    ]
